image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-browser
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore

vscode:
  extensions:
    - abusaidm.html-snippets
    - bradlc.vscode-tailwindcss
    - bung87.rails
    - castwide.solargraph
    - connorshea.vscode-ruby-test-adapter
    - dbaeumer.vscode-eslint
    - dsznajder.es7-react-js-snippets
    - ecmel.vscode-html-css
    - formulahendry.auto-close-tag
    - gencer.html-slim-scss-css-class-completion
    - HansUXdev.javascript-first-snippets
    - karunamurti.haml
    - ms-vscode.js-debug
    - pucelle.vscode-css-navigation
    - rebornix.ruby
    - runem.lit-plugin
    - samuelcolvin.jinjahtml
    - sianglim.slim
    - stylelint.vscode-stylelint
    - vscode.css-language-features
    - vscode.docker
    - vscode.html-language-features
    - vscode.image-preview
    - vscode.json-language-features
    - vscode.markdown-language-features
    - wingrunr21.vscode-ruby
    - Zignd.html-css-class-completion
